# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

# be polite
alias please='sudo'

# ssh
alias sshics='ssh -p 20022 luyiming@127.0.0.1'
alias sshvps='ssh root@159.203.197.219'
alias startics='sudo docker start ics-vm'
alias stopics='sudo docker stop ics-vm'

# tmux
alias ta='tmux attach'
alias tl='tmux ls'
alias tmux='tmux -2' # tmux with color
alias t='tmux'

# Shortcuts
alias tree='tree -C' # tree with color
alias t1='tree -L 1'
alias t2='tree -L 2'
alias t3='tree -L 3'
alias t4='tree -L 4'

# network
alias lg='python3 ~/.dotfiles/bin/login_campus_network.py'
alias pingnet='ping www.baidu.com -c 4'
alias hosts='sudo vim /etc/hosts'
alias curl='curl --socks5 127.0.0.1:1080'

# verbose
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias df='df -h'
alias du='du -h'

alias ls="ls --color"
alias l="ls -CFhl"
alias la="ls -AF"
alias lsd="ls -lAhF | grep --color=never '^d'"
alias ll='ls -ahlF'

# IP addresses
alias ip="ifconfig eth0 | grep -o --color=never '\(HWaddr \([a-fA-F0-9]\+:\)\{5\}[a-fA-F0-9]\+\)\|\(inet addr:\([0-9]\+\.\)\{3\}[0-9]\+\)'"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# misc
alias cdd='cd -'  # back to last directory
alias mc='java -jar /opt/Minecraft/HMCL.jar'
alias top10='print -l  ${(o)history%% *} | uniq -c | sort -nr | head -n 10'
alias fuck='TF_CMD=$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 TF_SHELL_ALIASES=$(alias) thefuck $(fc -ln -1 | tail -n 1)) && eval $TF_CMD && print -s $TF_CMD'


PATH=$PATH:$HOME/.dotfiles/bin
PATH=$PATH:/opt/IDEA/bin
PATH=$PATH:/opt/android-studio/bin
PATH=$PATH:/opt/clion-2016.2.3/bin
PATH=$PATH:/opt/phantomjs-2.1.1-linux-x86_64/bin
PATH=$PATH:/opt/node-v6.9.2-linux-x64/bin
PATH=$PATH:/opt/WebStorm-163.9166.30/bin

# java environ
export JAVA_HOME=/opt/java
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=$PATH:${JAVA_HOME}/bin

stty -ixon #disable CTRL+S Ctrl+Q, for vim

# fix mouse speed
[ -f $HOME/.dotfiles/bin/fix-mouse.sh ] && source $HOME/.dotfiles/bin/fix-mouse.sh

# change custom colors
eval "$(dircolors ~/.dircolors)"

# put you own local configs in ~/.zshrc.local
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
