# Path to your oh-my-zsh installation.
  export ZSH=/home/magnolias/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

  export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

alias pingnet='ping www.baidu.com -c 4'
alias i='sudo apt-get install'
alias s='apt-cache search'
alias r='apt-get --purge remove'

# ssh
alias sshics='ssh luyiming@192.168.56.101'

# tmux
alias ta='tmux attach'
alias tl='tmux ls'
alias tmux='tmux -2' # tmux with color
curl='curl --socks5 127.0.0.1:1080'
alias cdd='cd -'  # back to last directory
# Shortcuts
alias tree='tree -C' # tree with color
alias intlog='python3 ~/dotfiles/bin/login_campus_network.py'

# 命令别名
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias df='df -h'
alias du='du -h'

alias ls="ls --color"
# List all files colorized in long format
alias l="ls -CF"
# List all files colorized in long format, including dot files
alias la="ls -AF"
# List only directories
alias lsd="ls -lAhF | grep --color=never '^d'"
alias ll='ls -ahlF'

alias hosts='sudo vim /etc/hosts'

# IP addresses
alias ip="ifconfig|grep broadcast"  # List IPs
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# 快捷
alias d="cd ~/Dropbox"
alias dl="cd ~/下载"
alias dt="cd ~/桌面"
alias dg="cd ~/Github"

# 用特定应用打开特定后缀文件
alias -s pdf=okular
alias -s jpg=eog
alias -s png=eog
alias -s avi=vlc
alias -s mkv=vlc

#路径别名
#进入相应的路径时只要 cd ~xxx
hash -d g="~/Github"
hash -d e="/etc/"
hash -d d="$HOME/桌面/"
hash -d dl="$HOME/下载/"
hash -d p="$HOME/图片/"

hash -d PIC="$HOME/图片"
hash -d DOC="$HOME/文档"
hash -d DOWN="$HOME/下载"
hash -d MUSIC="$HOME/音乐"
hash -d DESK="$HOME/桌面"
hash -d SOFT="$HOME/软件"
hash -d MOV="$HOME/视频"

# 环境变量:
PATH=$PATH:~/dotfiles/bin:~/IDEA/bin:~/android-studio/bin

#安装JAVA至~目录
# 将jdk_version改名为java
export JAVA_HOME=~/java
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=$PATH:${JAVA_HOME}/bin

#历史命令 top10
alias top10='print -l  ${(o)history%% *} | uniq -c | sort -nr | head -n 10'

stty -ixon #禁用CTRL+S Ctrl+Q 用于vim
